version: "3"

services:
  web:
    image: nginx:alpine
    networks:
      - horus-net

  wiki:
    image: nginx:alpine
    networks:
      - horus-net

  proxy:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - horus-net
    volumes:
      - "./proxy/config/nginx.conf:/etc/nginx/nginx.conf:ro"

networks:
  horus-net:
